# **1. Import Library**

Pada tahap ini, Anda perlu mengimpor beberapa pustaka (library) Python yang dibutuhkan untuk analisis data dan pembangunan model machine learning.

In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report

# **2. Memuat Dataset dari Hasil Clustering**

Memuat dataset hasil clustering dari file CSV ke dalam variabel DataFrame.

In [2]:
df_original = pd.read_csv("Dataset_inisiasi.csv")
df_original

TransactionID AccountID  TransactionAmount  ... AccountBalance PreviousTransactionDate label
0         TX000001   AC00128              14.09  ...        5112.21     2024-11-04 08:08:08     2
1         TX000002   AC00455             376.24  ...       13758.91     2024-11-04 08:09:35     0
2         TX000003   AC00019             126.29  ...        1122.35     2024-11-04 08:07:04     1
3         TX000004   AC00070             184.50  ...        8569.06     2024-11-04 08:09:06     2
4         TX000005   AC00411              13.45  ...        7429.40     2024-11-04 08:06:39     2
...            ...       ...                ...  ...            ...                     ...   ...
2507      TX002508   AC00297             856.21  ...       12690.79     2024-11-04 08:11:29     0
2508      TX002509   AC00322             251.54  ...         254.75     2024-11-04 08:11:42     1
2509      TX002510   AC00095              28.63  ...        3382.91     2024-11-04 08:08:39     1
2510      TX002511   AC00118             185.97  ...        1776.91     2024-11-04 08:12:22     1
2511      TX002512   AC00009             243.08  ...         131.25     2024-11-04 08:07:49     1

[2512 rows x 17 columns]

# **3. Data Splitting**

Tahap Data Splitting bertujuan untuk memisahkan dataset menjadi dua bagian: data latih (training set) dan data uji (test set).

In [5]:
features = ["TransactionAmount","CustomerAge","TransactionDuration","AccountBalance"]

X_train, X_test, y_train, y_test = train_test_split(df_original[features], df_original["label"], test_size=0.2, random_state=42)

# **4. Membangun Model Klasifikasi**


## **a. Membangun Model Klasifikasi**

Setelah memilih algoritma klasifikasi yang sesuai, langkah selanjutnya adalah melatih model menggunakan data latih.

Berikut adalah rekomendasi tahapannya.
1. Pilih algoritma klasifikasi yang sesuai, seperti Logistic Regression, Decision Tree, Random Forest, atau K-Nearest Neighbors (KNN).
2. Latih model menggunakan data latih.

In [8]:
models = {
    "Decision Tree": DecisionTreeClassifier,
    "Random Forest": RandomForestClassifier,
    "K-Nearest Neighbors": KNeighborsClassifier,
}

predictions = {}

for name, model in models.items():
  if name != "K-Nearest Neighbors":
    clf = model(random_state=42)
  else:
    clf = model()
  clf = clf.fit(X_train, y_train)
  predictions[name] = clf.predict(X_test)

Saya akan memilih 3 algoritma untuk melakukan klasifikasi ini, yaitu KNN, Decision Tree dan Random Forest. Ketiga algoritma ini saya pilih karena memiliki kemampuan yang baik dalam menangani data numerik.

Selain itu, ketiga algoritma ini juga dikenal sebagai algoritma pemenang lomba Data Mining, terutama Random Forest.

## **b. Evaluasi Model Klasifikasi**

Berikut adalah **rekomendasi** tahapannya.
1. Lakukan prediksi menggunakan data uji.
2. Hitung metrik evaluasi seperti Accuracy dan F1-Score (Opsional: Precision dan Recall).
3. Buat confusion matrix untuk melihat detail prediksi benar dan salah.

In [22]:
metrics = {
    "Confusion Matrix": confusion_matrix,
    "Classification Report": classification_report
}

for model_name, y_pred in predictions.items():
  print(model_name)
  for metric, fx in metrics.items():
    print(metric, "\n", fx(y_test, y_pred), "\n")

Decision Tree
Confusion Matrix 
 [[ 81   0   0]
 [  0 221   1]
 [  0   0 200]] 

Classification Report 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        81
           1       1.00      1.00      1.00       222
           2       1.00      1.00      1.00       200

    accuracy                           1.00       503
   macro avg       1.00      1.00      1.00       503
weighted avg       1.00      1.00      1.00       503
 

Random Forest
Confusion Matrix 
 [[ 81   0   0]
 [  0 221   1]
 [  0   0 200]] 

Classification Report 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        81
           1       1.00      1.00      1.00       222
           2       1.00      1.00      1.00       200

    accuracy                           1.00       503
   macro avg       1.00      1.00      1.00       503
weighted avg       1.00      1.00      1.00       503
 

K-Nearest Neighbors
Conf

Hasil dari ketiga model yang dipilih sangat memuaskan secara nominal, namun justru hal ini menimbulkan kecurigaan bahwa terjadi overfitting pada model.

Selain itu, performa paling baik dimiliki oleh Random Forest Classifier sesuai prediksi awal.

## **c. Tuning Model Klasifikasi (Optional)**

Gunakan GridSearchCV, RandomizedSearchCV, atau metode lainnya untuk mencari kombinasi hyperparameter terbaik

In [ ]:
#Type your code here

## **d. Evaluasi Model Klasifikasi setelah Tuning (Optional)**

Berikut adalah rekomendasi tahapannya.
1. Gunakan model dengan hyperparameter terbaik.
2. Hitung ulang metrik evaluasi untuk melihat apakah ada peningkatan performa.

In [ ]:
#Type your code here

## **e. Analisis Hasil Evaluasi Model Klasifikasi**

Berikut adalah **rekomendasi** tahapannya.
1. Bandingkan hasil evaluasi sebelum dan setelah tuning (jika dilakukan).
2. Identifikasi kelemahan model, seperti:
  - Precision atau Recall rendah untuk kelas tertentu.
  - Apakah model mengalami overfitting atau underfitting?
3. Berikan rekomendasi tindakan lanjutan, seperti mengumpulkan data tambahan atau mencoba algoritma lain jika hasil belum memuaskan.

Model yang dibuat telah menghasilkan prediksi yang memuaskan, namun perlu digarisbawahi bahwa ini bisa menandakan terjadinya overfitting pada model, yang disebabkan oleh dataset yang tidak cukup bervariasi, sehingga data training dan data testing terlihat sama saja.

Maka dari itu, saran tindakan yang harus dilakukan adalah melakukan penambahan data, baik dengan cara mencari data di internet maupun dengan menambahkan data sintetis.